# Generated by Django 3.2 on 2021-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210423_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=16)),
                ('device_info', models.CharField(max_length=500)),
                ('login_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
