# Generated by Django 3.2 on 2021-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
