# Generated by Django 3.2 on 2021-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userhistory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
