const fs = require('fs');
const path = require("path");
const os = require('os-utils');
const Dropzone = require(__dirname + "\\plugins\\dropzone\\dropzone.js")
const crypto = require('crypto');
const open = require('open');
const FormData = require('form-data')
const axios = require('axios')
const { ipcRenderer } = require( 'electron' );