# Generated by Django 3.2 on 2021-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=32)),
                ('iv', models.CharField(max_length=16)),
            ],
        ),
    ]
